# Generated by Django 2.2.3 on 2019-07-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0002_comment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ratings_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='ratings_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='ratings_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='ratings_up',
            field=models.IntegerField(default=0),
        ),
    ]
