# Generated by Django 2.2.3 on 2019-07-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0002_comment_vote'),
        ('MECboard', '0003_auto_20190720_1817'),
    ]

    operations = [
    ]
