# Generated by Django 2.2.3 on 2019-07-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0004_merge_20190722_1200'),
        ('MECboard', '0005_auto_20190722_1610'),
    ]

    operations = [
    ]
