# Generated by Django 2.2.3 on 2019-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0010_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media/thumail'),
        ),
    ]
