# Generated by Django 2.2.3 on 2019-08-03 04:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0012_remove_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='media/default.jpeg', upload_to='media/thumnail'),
        ),
    ]
