# Generated by Django 2.2.3 on 2019-08-06 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0015_auto_20190803_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('board_idx', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ratings_up', models.IntegerField(default=0)),
                ('ratings_down', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('filename', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('filesize', models.IntegerField(default=0)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='media/images')),
            ],
        ),
    ]
