# Generated by Django 2.2.3 on 2019-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0016_evidence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.AddField(
            model_name='comment',
            name='evidence',
            field=models.BooleanField(default=False),
        ),
    ]
